- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.4
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
      files: YaboAI.py
    # Run the formatter.
    - id: ruff-format
      files: YaboAI.py
